### PR TITLE
add splitEvery

### PR DESCRIPTION
**Pull request by paralax**
this PR adds splitEvery, same interface as Haskell's Data.List.Split.splitEvery

### CODE REVIEW

**Comment by rehno-lindeque** [comment]
Great, thank you! I notice that it's exported as `groupInto` instead of `splitEvery` but I'll fix that quickly myself.

**Comment by rehno-lindeque** [comment]
Oh actually sorry, I merged before thinking this through - I'm going to move this over to a new package. I hope you don't mind. Since there are so many possible splitting functions I think it can actually be a standalone package, I did something like this already with [elm-string-split](package.elm-lang.org/packages/circuithub/elm-string-split/latest) - quickly going to create a `elm-list-split` now that has `chunksOfLeft` and `chunksOfRight`.

**Comment by rehno-lindeque** [comment]
Please see the [List.Split](http://package.elm-lang.org/packages/circuithub/elm-list-split/latest/List-Split) module in [elm-list-split](http://package.elm-lang.org/packages/circuithub/elm-list-split/latest) and feel free to make suggestions!

**Comment by paralax** [comment]
sounds good, thanks!

i have a few more functions to add, will put in the right place (-extras or
-split). working on permutations and such, porting from F#.

thanks again for the quick discussion.
- jose

On Fri, May 29, 2015 at 5:42 AM, Rehno Lindeque notifications@github.com
wrote:

> Please see the List.Split
> http://package.elm-lang.org/packages/circuithub/elm-list-split/latest/List-Split
> module in elm-list-split
> http://package.elm-lang.org/packages/circuithub/elm-list-split/latest
> and feel free to make suggestions!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/circuithub/elm-list-extra/pull/8#issuecomment-106759588
> .

## 

jose nazario
For Privacy Act and Paperwork Reduction Act Notice, see page 2

**Comment by rehno-lindeque** [comment]
No problem, I'm excited to get contributions on these.

**Pull request merged**
