### PR TITLE
Support Elm 0.16

### PR DESCRIPTION
**Pull request by rtfeldman**
Relaxes version bounds, removes multiway if, and resolves some incomplete pattern matches.

### CODE REVIEW

**Comment by rtfeldman** [comment]
@rehno-lindeque mind double-checking that https://github.com/circuithub/elm-list-extra/commit/ff2a432992382892a8b22031d96b610159f7fe62 looks ok before I merge this?

**Comment by rehno-lindeque** [comment]
Wow, a flood of contributions. Thanks so much!

As far as I can tell everything in here looks ok to me. I didn't write any of the `scan*` functions myself, so I haven't even tested them out. Please feel free to merge and publish!

**Comment by codedmart** [comment]
Just browsed over as an extra pair of eyes. Looks good to me.

**Comment by rtfeldman** [comment]
Thanks!

**Pull request merged**
