### PR TITLE
Added updateAt and updateIfIndex

### PR DESCRIPTION
**Pull request by mdgriffith**
updateAt - run an update function on the element at a specific index.
updateIfIndex - run an update on a element where the index satisfies a predicate.
catMaybes - concatenate a list of maybes, eliminating the Nothing's

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
I see a conceptual/API conflict between the type of `updateAt` here and the type of the already existing `setAt`. A reasonable expectation when having both these functions would be that `setAt i x` is equivalent to `updateAt i (always x)`. But that would not work out now.

The solution could be to change type and behavior of `updateAt` here, or change type and behavior of `setAt`. But I think things should be made consistent _some_ way.

My preference is changing the type of `updateAt` to return a `Maybe`. The reason is that while the names `updateIf` and `updateIfIndex` do convey that maybe no actual update will take place ("`...If...`"), the name `updateAt` sounds as if the list obtained as output will really have been updated. Since that may not be true, since the index passed might be out of range, it would be better that `updateAt` has a `Maybe` return type and returns `Nothing` when the index was out of range and thus the passed update function could not even be applied in a meaningful way.

**Comment by jvoigtlaender** [comment]
Also, `catMaybes` is just `List.filterMap identity`.

I propose to:
- either, use that as definition for `List.Extra.catMaybes`
- or, not have `List.Extra.catMaybes` at all (since it's so readily available from `core` through `filterMap identity`)

My preference is for the second option.

**Comment by jvoigtlaender** [comment]
Concerning `updateAt` vs. `setAt`, I prefer changing the type of `updateAt` to return a `Maybe`. The reason is that while the names `updateIf` and `updateIfIndex` do convey that maybe no actual update will take place ("`...If...`"), the name `updateAt` sounds as if the list obtained as output will really have been updated. Since that may no be true, since the index passed might be out of range, it would be better that `updateAt` has a `Maybe` return type and returns `Nothing` when the index was out of range and thus the passed update function could not even be applied in a meaningful way.

**Comment by jvoigtlaender** [comment]
Sorry, confused the catMaybes options. My preference is for the second option there.

**Comment by mdgriffith** [comment]
Hey!  Thanks for taking a look.

I'm good with switching updateAt to returning a maybe list.   I can get the old result easily using

`Maybe.withDefault list (updateAt i update list)`

which is more explicit.

I didn't notice the filterMap solution for catMaybes, I agree that's simple enough to not warrant catMaybes.

If that sounds good, I'll revise the PR

**Comment by jvoigtlaender** [comment]
I'm fine with how the PR now looks. Since I didn't sign up to be maintainer for this repository, I shouldn't make the decision about merging the PR all on my own. So will wait for someone else's additional okay first.

**Comment by jvoigtlaender** [comment]
@abadi199, merge this?

**Pull request merged**
