### PR TITLE
Add range function

### PR DESCRIPTION
**Pull request by ghost**
I've included the `range` function, similar to the Elixir function of the same name.

### CODE REVIEW

**Comment by codedmart** [comment]
@category Thanks for the PR. Would you mind squashing your commits?

**Comment by ghost** [comment]
@codedmart Thanks for the heads up - that's been done following [this](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) guide.

**Comment by eeue56** [comment]
@category why does this exist? `[1..5]` does forward ranges, `List.reverse [1..5]` does flipped ranges

**Comment by abadi199** [comment]
I agree with @eeue56 and will close this PR unless someone can give a use case where can't be done with the standard elm syntax.

**Pull request closed without merging**
