### PR TITLE
Added replace: replaces old with new within a list

### PR DESCRIPTION
**Pull request by z5h**
Makes it possible to create friendlier implementations
of code like this:
https://github.com/evancz/elm-todomvc/blob/bc37c9b97db9e1c1d5db9debf0d900c77461e584/Todo.elm#L108-L111

### CODE REVIEW

**Comment by rtfeldman** [comment]
Hm...how would you use this `replace` to rewrite [that code](https://github.com/evancz/elm-todomvc/blob/bc37c9b97db9e1c1d5db9debf0d900c77461e584/Todo.elm#L108-L111)?

Seems like the `t.id == id` part would make it incompatible, yeah?

**Comment by rehno-lindeque** [comment]
Mmmm, yes I think you might actually be looking for a function like `mapOn`, similar to say [sortOn](http://hackage.haskell.org/package/extra-1.4.1/docs/Data-List-Extra.html#v:sortOn).

PS I wouldn't be opposed to adding this function, but perhaps it might make sense to reserve `replace` for a function with this type signature?

```
replace : List a -> List a -> List a -> List a
```

That is, Haskell has a function like 

```
replace : Text -> Text -> Text -> Text
```

Might I suggest `replaceElement`?

I only managed to find a couple of lonely looking implementations of [replace : a -> a -> [a] -> [a]](http://hayoo.fh-wedel.de/?query=a+-%3E+a+-%3E+%5Ba%5D+-%3E+%5Ba%5D) in Haskell.

**Comment by z5h** [comment]
A few ideas.

In my own code, my action type constructors are `ActionType Record ...` instead of `ActionType Id ...`
So my handlers look like:

```
EditName entry name ->
  let newEntry = {entry | name <- name}
  in
    { model | 
      entries <- replace entry newEntry model.entries
    }
```

If that's no good. Perhaps we can settle on:

```
replaceIf : (a -> Bool) -> a -> List a -> List a
replaceIf pred new list=
  let replace item =
    if | pred item -> new
       | otherwise-> item
  in List.map replace list
```

My biggest concern is that a newcomer wanting to update a value in a List will have no idea what to do.

Update.
@rehno-lindeque yes, replaceElement, and replace List -> List -> List -> List could work too.

**Comment by rehno-lindeque** [comment]
> Mmmm, yes I think you might actually be looking for a function like mapOn, similar to say sortOn.

Sorry, ignore this comment. I don't know what I was thinking. This would have been more like `mapIf` using that nomenclature, which I suppose is similar to your `replaceIf`.

I think I'm ok with `replaceIf`, what do you think @rtfeldman?

**Comment by rehno-lindeque** [comment]
PS, I'm not a formatting-nazi usually, but I'm a bit wary of the multi-way if syntax with this proposal floating around at the moment https://github.com/elm-lang/elm-plans/issues/3 (I don't want to go through all my packages in order to clean up later :sweat_smile:)

**Comment by z5h** [comment]
So the current candidate is:

```
replaceIf : (a -> Bool) -> a -> List a -> List a
replaceIf test new list =
  List.map (\item -> if test item then new else item) list
```

**Comment by rtfeldman** [comment]
:+1: makes sense to me!

**Comment by rehno-lindeque** [comment]
Sounds good to me. Please remember to add it to the export list at the top and the `@docs` too.

**Comment by z5h** [comment]
Will do. What's the preferred pull-request protocol? Just commit on top of this, or close this and create a new PR?

**Comment by rehno-lindeque** [comment]
It doesn't really matter to me, I'm not picky. Some maintainers prefer if you rebase in order to squash all commits into one.

I tend to `git commit --amend ; git push origin mybranch --force` whenever I'm feeling confident, in order to rewrite history.

**Comment by rehno-lindeque** [comment]
Oh you made the commit, this is fine. I'll merge

**Comment by rehno-lindeque** [comment]
Published as [3.2.0](http://package.elm-lang.org/packages/circuithub/elm-list-extra/3.2.0/List-Extra#replaceIf). Thank you!

**Pull request merged**
