### PR TITLE
Added setAt and removeAt.

### PR DESCRIPTION
**Pull request by abingham**
Added functions for setting/replacing (would "replaceAt" be a better name?) and removing elements by index.

### CODE REVIEW

**Comment by codedmart** [comment]
@abingham Looks like some conflicts need to be resolved.

**Comment by abingham** [comment]
OK, I think it's in better shape now.

**Comment by lukewestby** [comment]
Should the list arguments be last?

**Comment by abingham** [comment]
I patterned the signatures off of `getAt` which has the list argument first. But it doesn't bother me much either way. What's the argument for putting the list argument last?

**Comment by jvoigtlaender** [comment]
http://package.elm-lang.org/help/design-guidelines#the-data-structure-is-always-the-last-argument

**Comment by abingham** [comment]
OK, I've updated the functions now. Should I make an issue for changing `getAt` accordingly?

**Comment by jvoigtlaender** [comment]
I've taken a look at the implementations now. Seem wrong to me. Think about what happens when you call them with a negative `index`. Certainly a negative index means "out of range", but what actually happens for a negative index does not agree with what the documentation says about what happens for out of range index.

Moreover, the data structure is still not the last argument in your type for `setAt : Int -> List a -> a -> Maybe (List a)`.

**Comment by jvoigtlaender** [comment]
About `getAt`, yes, its type should be changed to `getAt : Int -> List a -> Maybe a`.

**Comment by abingham** [comment]
You're right, that was a sloppy commit. Sorry about that.

Regarding things like negative indices, what's idiomatic in Elm? I can't find any indication of how negative indices are handled in e.g. `List.drop`, yet it certainly doesn't return `Nothing` (that's not even an option, given the return type). I think when I originally wrote this I had a naive hope that the underlying take and drop implementations had a consistent, composable behavior over all indices, but I clearly didn't take the time to check thoroughly :-/

In any event, I've added explicit handling for negative indices to both functions.

**Comment by jvoigtlaender** [comment]
I think you handle negative indices exactly right now. Am merging.

**Pull request merged**
