### PR TITLE
Added updateIf and deleteIf

### PR DESCRIPTION
**Pull request by seanhess**
I added two functions along the lines of `replaceIf`, that I keep needing in my projects. 

`updateIf` is a generalization of `replaceIf` and allows you to provide an update function. This has ended up being extremely useful in a large number of situations.  

`deleteIf` is just sugar over filter, I don't have a strong opinion about this.

### CODE REVIEW

**Comment by agrafix** [comment]
I would suggest a simpler signature for `updateIf`: something like `(a -> Maybe a) -> List a -> List a`, `Just a` means update, `Nothing` means keep existing value.

**Comment by seanhess** [comment]
@agrafix That would work. However, I usually already have functions that fit the other signature. For example, I've already defined the following

```
byId : String -> MyObject -> Bool
byId id obj = obj.id == id

setName : String -> MyObject -> MyObject
setName nm = { obj | name = nm }
```

The above are useful in a wide variety of situations, like calling `List.find`, `List.replaceIf`, or updating using `setName` in response to an `elm-html` event, for example, before passing it off to an action. 

So I think while the proposed signature for `updateIf` is more complex, it's also more composable. But I'll defer to you on this. What do you think?

**Comment by eeue56** [comment]
`updateIf` is something we will want to use. I like this. Can you add it to the exposed stuff and docs?

**Comment by lukewestby** [comment]
@seanhess any updates?

**Comment by seanhess** [comment]
@agrafix How do you feel about merging it as it stands?

**Comment by codedmart** [comment]
@agrafix As it sounds like this is useful for others. I am going to plan on merging this today unless someone says otherwise.

**Comment by lukewestby** [comment]
@codedmart @seanhess i think the functions just need to be added to the exposed values and doc list

**Comment by seanhess** [comment]
@lukewestby Done. Rebased and squashed into a single commit. Look good?

**Pull request merged**
