### PR TITLE
Reversed parameter order for getAt.

### PR DESCRIPTION
**Pull request by abingham**
This addresses #36

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Oh, actually for the operator version I'd argue for keeping the old order. That operator is known from other languages and it would be strange to switch its arguments.

**Comment by abingham** [comment]
I can squash these into one commit, if you'd like.

**Comment by jvoigtlaender** [comment]
I'm happy merging it without squashing. Or an admin could change the repository settings so that "squash on merge" becomes available.

In any case, due to the type change of `getAt` (which I fully support), I'll wait for another person with commit rights to voice support as well before I actually do the merge.

**Comment by eeue56** [comment]
I agree 👍

**Pull request merged**
